import type { StoredSupplierPromotion } from "../model";

export const initialSupplierPromotions: readonly StoredSupplierPromotion[] = [
  {
    id: "PROMO-1001",
    accountId: "supplier-ararat-harvest",
    name: "Olive oil service price",
    description: "A locked-in price for the bottle used across your service.",
    type: "FixedPrice",
    status: "Active",
    startDate: "2026-09-01T00:00:00Z",
    endDate: "2026-09-30T23:59:59Z",
    productIds: ["PROD-1002"],
    discountScope: "specific-options",
    discountOptionKeys: ["PROD-1002:option-1"],
    fixedPrices: { "PROD-1002:option-1": "22000" },
    eligibility: "all-customers",
    eligibleCustomerIds: [],
    applyOnIndividualPricing: false,
    isBannerEnabled: true,
    display: "both",
    brandColorFallback: "#c18517",
    createdAt: "2026-09-01T00:00:00Z",
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "PROMO-1003",
    accountId: "supplier-mare-terra",
    name: "Pantry pairing",
    description: "Restock your olive oil and pick a pantry companion for free.",
    type: "BuyXGetY",
    status: "Active",
    startDate: "2026-09-01T00:00:00Z",
    endDate: "2026-09-30T23:59:59Z",
    productIds: ["olive-oil", "balsamic-vinegar", "castelvetrano-olives"],
    discountOptionKeys: [],
    fixedPrices: {},
    triggerProductId: "olive-oil",
    triggerOptionId: "bottle",
    triggerQuantity: "2",
    targetProductId: "balsamic-vinegar",
    targetOptionId: "bottle",
    targetQuantity: "1",
    giftChoices: [
      { productId: "balsamic-vinegar", optionId: "bottle" },
      { productId: "castelvetrano-olives", optionId: "jar" },
    ],
    eligibility: "all-customers",
    eligibleCustomerIds: [],
    applyOnIndividualPricing: false,
    isBannerEnabled: true,
    display: "both",
    brandColorFallback: "#765ba7",
    createdAt: "2026-09-01T00:00:00Z",
    updatedAt: "2026-09-01T00:00:00Z",
  },
];
