import type { StoredSupplierProduct } from "../model";

const supplierAccountId = "supplier-ararat-harvest";

export const initialSupplierProducts: readonly StoredSupplierProduct[] = [
  {
    id: "PROD-1001",
    accountId: supplierAccountId,
    name: "Organic Citrus Mix",
    description: "A bright seasonal mix of hand-selected organic citrus, packed fresh for professional kitchens.",
    categoryIds: ["supplier-category-1"],
    code: "OCM-204",
    imageUrl: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=200&q=80",
    status: "Active",
    createdAt: "2026-08-26",
    sellingOptions: [
      { id: "option-1", quantity: 1, unitType: "Package", piecesPerPackage: 12, price: 18_500, compareAtPrice: 21_000, minimumOrderQuantity: 1, companyPrices: [{ resourceId: "horeca-blue-lagoon", individualPrice: 16_750 }] },
      { id: "option-2", quantity: 6, unitType: "Package", piecesPerPackage: 12, price: 102_000, minimumOrderQuantity: 2, companyPrices: [] },
    ],
  },
  {
    id: "PROD-1002",
    accountId: supplierAccountId,
    name: "Premium Extra Virgin Olive Oil",
    description: "Cold-pressed extra virgin olive oil for professional kitchens.",
    categoryIds: ["supplier-category-4"],
    code: "EVO-118",
    imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=200&q=80",
    status: "Active",
    createdAt: "2026-08-24",
    sellingOptions: [
      { id: "option-1", quantity: 1, unitType: "Liter (լ)", price: 24_000, minimumOrderQuantity: 2, companyPrices: [] },
      { id: "option-2", quantity: 6, unitType: "Package", price: 136_000, minimumOrderQuantity: 1, companyPrices: [] },
    ],
  },
  {
    id: "PROD-1003",
    accountId: supplierAccountId,
    name: "Artisan Basil Bundle",
    description: "Aromatic basil bundled fresh for chef-led menus.",
    categoryIds: ["supplier-category-2"],
    imageUrl: "https://images.unsplash.com/photo-1461354464878-ad92f492a5a0?auto=format&fit=crop&w=200&q=80",
    status: "Unlisted",
    createdAt: "2026-08-21",
    sellingOptions: [
      { id: "option-1", quantity: 1, unitType: "Piece (հատ)", price: 9_750, minimumOrderQuantity: 3, companyPrices: [] },
      { id: "option-2", quantity: 12, unitType: "Package", piecesPerPackage: 12, price: 109_000, minimumOrderQuantity: 1, companyPrices: [] },
    ],
  },
  {
    id: "PROD-1004",
    accountId: supplierAccountId,
    name: "Farmhouse Cheese Selection",
    description: "A rotating selection of farmhouse cheeses.",
    categoryIds: ["supplier-category-5"],
    code: "FCS-402",
    imageUrl: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?auto=format&fit=crop&w=200&q=80",
    status: "Active",
    createdAt: "2026-08-18",
    sellingOptions: [
      { id: "option-1", quantity: 1, unitType: "Kilogram (կգ)", price: 31_250, minimumOrderQuantity: 1, companyPrices: [] },
      { id: "option-2", quantity: 3, unitType: "Package", price: 88_000, minimumOrderQuantity: 1, companyPrices: [] },
    ],
  },
  {
    id: "PROD-1005",
    accountId: supplierAccountId,
    name: "Sunrise Berry Box",
    description: "Seasonal berries selected for breakfast and pastry programs.",
    categoryIds: ["supplier-category-3"],
    code: "SBB-071",
    imageUrl: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=200&q=80",
    status: "Inactive",
    createdAt: "2026-08-12",
    sellingOptions: [
      { id: "option-1", quantity: 1, unitType: "Package", price: 16_000, minimumOrderQuantity: 1, companyPrices: [] },
      { id: "option-2", quantity: 4, unitType: "Package", price: 60_000, minimumOrderQuantity: 1, companyPrices: [] },
    ],
  },
  {
    id: "olive-oil",
    accountId: "supplier-mare-terra",
    name: "Extra virgin olive oil",
    description: "Cold-pressed extra virgin olive oil for daily service and finishing.",
    categoryIds: ["mare-terra-pantry"],
    code: "MT-EVO-001",
    imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=900&q=85",
    status: "Active",
    createdAt: "2026-09-01",
    sellingOptions: [
      { id: "bottle", quantity: 1, unitType: "bottle (1 L)", price: 8_900, minimumOrderQuantity: 1, companyPrices: [] },
      { id: "case", quantity: 6, unitType: "bottles (1 L)", price: 50_400, minimumOrderQuantity: 1, companyPrices: [] },
    ],
  },
  {
    id: "balsamic-vinegar",
    accountId: "supplier-mare-terra",
    name: "Aged balsamic vinegar",
    description: "A balanced aged balsamic for dressings, reductions, and finishing.",
    categoryIds: ["mare-terra-pantry"],
    code: "MT-BAL-002",
    imageUrl: "https://images.unsplash.com/photo-1603046891744-76e6300c6e53?auto=format&fit=crop&w=900&q=85",
    status: "Active",
    createdAt: "2026-09-01",
    sellingOptions: [
      { id: "bottle", quantity: 1, unitType: "bottle (500 ml)", price: 4_200, minimumOrderQuantity: 1, companyPrices: [] },
      { id: "case", quantity: 6, unitType: "bottles (500 ml)", price: 22_800, minimumOrderQuantity: 1, companyPrices: [] },
    ],
  },
  {
    id: "castelvetrano-olives",
    accountId: "supplier-mare-terra",
    name: "Castelvetrano green olives",
    description: "Bright, buttery green olives packed for sharing plates and bar snacks.",
    categoryIds: ["mare-terra-pantry"],
    code: "MT-OLV-003",
    imageUrl: "https://images.unsplash.com/photo-1593001872095-7d5b3868fb1d?auto=format&fit=crop&w=900&q=85",
    status: "Active",
    createdAt: "2026-09-01",
    sellingOptions: [
      { id: "jar", quantity: 1, unitType: "jar (500 g)", price: 3_600, minimumOrderQuantity: 1, companyPrices: [] },
      { id: "case", quantity: 6, unitType: "jars (500 g)", price: 19_800, minimumOrderQuantity: 1, companyPrices: [] },
    ],
  },
];
